In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

songs_data_path = "../data/Music_Info.csv"
users_data_path =  "../data/User_Listening_History.csv"

In [3]:
songs_df = pd.read_csv(songs_data_path,usecols =['track_id','name','artist','spotify_preview_url'])
songs_df.head()

,track_id,name,artist,spotify_preview_url
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...

In [4]:
! pip install dask[dataframe]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dask[dataframe] in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (2026.7.1)
Requirement already satisfied: click>=8.1 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (8.4.1)
Requirement already satisfied: cloudpickle>=3.0.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (2025.12.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (25.0)
Requirement already satisfied: partd>=1.4.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (1.4.2)
Requirement already satisfied: pyyaml>=5.4.1 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (1.1.0)
Requirement already satisfied: pandas>=2.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (2.2.3)
Requirement already satisfied: pyarrow>=16.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from dask[dataframe]) (23.0.1)
Requirement already satisfied: colorama in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from click>=8.1->dask[dataframe]) (0.4.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from pandas>=2.0->dask[dataframe]) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from pandas>=2.0->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: locket in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from partd>=1.4.0->dask[dataframe]) (1.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import dask.dataframe as dd

df = dd.read_csv(users_data_path)
df.head(5)

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

In [6]:
df

Dask DataFrame Structure:
              track_id user_id playcount
npartitions=9
                string  string     int64
                   ...     ...       ...
...                ...     ...       ...
                   ...     ...       ...
                   ...     ...       ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(4b09a89))

In [7]:
df

Dask DataFrame Structure:
              track_id user_id playcount
npartitions=9
                string  string     int64
                   ...     ...       ...
...                ...     ...       ...
                   ...     ...       ...
                   ...     ...       ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(4b09a89))

In [8]:
! pip install graphviz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: graphviz in C:\Users\KIIT0001\AppData\Roaming\Python\Python313\site-packages (0.21)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
df.npartitions

9

In [10]:
unique_track = df.loc[:,'track_id'].nunique()

In [11]:
unique_track = unique_track.compute()
unique_track

np.int64(30459)

In [12]:
unique_users = df.loc[:,'user_id'].nunique()
unique_users = unique_users.compute()
unique_users

np.int64(962037)

In [13]:
unique_track_ids = df.loc[:,'track_id'].unique().compute()
unique_track_ids = unique_track_ids.tolist()
unique_track_ids

['TRLXSNR128F429361D',
 'TRPUGUW128F426BF6F',
 'TRISTWT128F1488FBB',
 'TRKPWGR128E078EE06',
 'TRXQJWK128F146DF76',
 'TRGASNY128F14696B0',
 'TRSQWMI128F932FC8A',
 'TRBVNWT128F93173BA',
 'TRBHQZM128F42A52D2',
 'TRSWJHK128F429EA6F',
 'TRRUZLF128F42396D0',
 'TRMPCGW128F92E0670',
 'TRJNMNC128F427ED16',
 'TRWCIAX128F42925BD',
 'TRGVKBK128F429EA2D',
 'TRGRPEU128F932BD78',
 'TRANEZZ128F92FFC06',
 'TRRYLYK128F92F89F6',
 'TRQGHWL128EF33FB48',
 'TRWZFIC128F933BCA3',
 'TRKSEEY12903CCD312',
 'TRBTCYJ128F92F9586',
 'TRQPRPK12903CCF3B6',
 'TRJSQQT128F149F9B4',
 'TREWPIM128F4261B51',
 'TRMZPXZ128F92F3495',
 'TRTGEVW128F14979BB',
 'TROUMHD128F9355B89',
 'TRKRNZF12903CB52BC',
 'TRBSBCX128F92DEF11',
 'TRXHDTA128F42A077A',
 'TRSJBLT128F429EA02',
 'TRTJYDU128F92E49EE',
 'TRDTMGK12903CC557F',
 'TRBOAJY128F14979B5',
 'TRBYDXV128F424888B',
 'TRCIOVJ128F429EB51',
 'TRYBFNR128F426BE3D',
 'TRWOYHS128F931EB5A',
 'TRNNLYM128F92EDE7F',
 'TRATHTH128F42BC347',
 'TRXERRS128F42969E4',
 'TRZPVLJ128F148D2F7',
 'TRGTVVB128F1485912',
 'TRFRJAY128F1465267',
 'TRHUNZT128C719654E',
 'TRRMVBR128F92F64BA',
 'TRXGMWP128E078253B',
 'TRACPOT128F92E9E61',
 'TRZLEQU128F4259AFD',
 'TRLOHWT128F42598CF',
 'TRWUBNZ128E07820C4',
 'TRPKQEL128E0795771',
 'TRWJYOT128F935572B',
 'TROSQKR128E078ECCB',
 'TRMGVXA128F147A025',
 'TRBPYAK12903CC2F2E',
 'TRKNOQE128F425BEF5',
 'TRLXPMB128EF342C12',
 'TROMZSY128F92F2F41',
 'TREZWTF128EF3447DF',
 'TRJAVOR128F9332C49',
 'TRJISIO128F145549E',
 'TRYRVDR128EF342B77',
 'TRJCVRS12903CD667C',
 'TRGHUIU12903CBBD0A',
 'TRBGDAX128F93497AB',
 'TRORKFK12903CA2760',
 'TRWYIQA128F148B32E',
 'TRMKRXO128F9339628',
 'TRZKHEE128F4234779',
 'TRJNEBY128E0783A4E',
 'TRKOMYY128F423EAEA',
 'TRCUCJV12903CEA641',
 'TRBOQBQ128F42B8BF4',
 'TRFTRHM128F93032DB',
 'TRLZOSW128F14522AA',
 'TRLLSRB128F14520BA',
 'TRXEFSQ128F92DC10C',
 'TRBBUHB128F4282729',
 'TRGOHEG128F4284129',
 'TRYPVPQ128F9329D34',
 'TRDTMRW128F9325CB1',
 'TREQTXJ128F92FFE9C',
 'TRCVSCB128F425BD4A',
 'TRCVEKZ128F429B0B0',
 'TRWJNEC128E079654F',
 'TRMADBK128F4270FCB',
 'TRCABHD12903CB6337',
 'TRWXFCU128EF351B77',
 'TRPSZSI128F423F041',
 'TRRQSBH128F421C976',
 'TROAKXG128EF35FBD1',
 'TRQMXMX128F4248268',
 'TRTDNFO128F92D5BF6',
 'TRBBWXA128F92CE697',
 'TRCSYZY128F93365E1',
 'TRTFFMQ128F92F8DB2',
 'TRNHRUA128F147733B',
 'TRSMXXG128F930C2F3',
 'TRJNPZO12903CFEDB9',
 'TRLAXOZ12903CFF90D',
 'TRQEZSL12903CB5079',
 'TRDVDZS12903CE108E',
 'TRMSVOJ128F9316F9D',
 'TRDZGLB128F148C848',
 'TREVRAJ128F42819AD',
 'TRGHNJM128F146930E',
 'TRNEIDS128F932A7A8',
 'TRXHGVR128E0791E5D',
 'TRMABFS12903CA9D0E',
 'TRMHQMH128F423EB56',
 'TRYHTWZ128F42370DD',
 'TRUHUNN128F92E58B5',
 'TRPOMJY128F1486DEC',
 'TRRJFXX128F427A71F',
 'TROOHYP128F4263C1E',
 'TRMYQER128F92C41BC',
 'TRJRIHX128F147CBC5',
 'TRQSEMJ128F4294F24',
 'TRVESUC128F1477267',
 'TROITAX128F429E9FD',
 'TRYFXPG128E078ECBD',
 'TRUNSXQ128E078B97D',
 'TRCRWHC128F92C260B',
 'TRJCQYE128F14A00EB',
 'TRXWQJL128EF351B64',
 'TRDVRIY128F424CDD0',
 'TRXYKRV128F4285828',
 'TRGRCDR128F931118C',
 'TRRTGSQ128F4298709',
 'TRIDVHX128F429870F',
 'TRNEWWX128F9336A1F',
 'TRTXZWO128F4228946',
 'TRDLDBZ128E0781C8A',
 'TREWOPE128E0782228',
 'TRILYFA128F932BDC4',
 'TRRSWEO128F429312A',
 'TRDBBVV128F4281CB6',
 'TRUKSVZ128F92EF91B',
 'TRHDTQE128F427B8D6',
 'TRXLYHW128F429B905',
 'TRBROBA128F9321BC2',
 'TRGTPNQ128F424F973',
 'TRNHKGL128E07912F9',
 'TRAFAJC128E078888B',
 'TRBHJPQ128E078ED8F',
 'TRXNOES128F9301FD2',
 'TRRQXOZ128E07860F8',
 'TRUNYCG128F423A553',
 'TRRRMKC128E0792990',
 'TRAXQYP128F930458D',
 'TRUCWXA128F92E4944',
 'TRWCVWH128F4284EE5',
 'TRKDXYA128F933A93C',
 'TRVDWIE128F1452CB2',
 'TRESKNU128E078A187',
 'TRMSBSS128E0798916',
 'TRVWWQO128F931A3CD',
 'TRVSFIB128F9347281',
 'TRSATRQ128E0782786',
 'TRRRVNT128E079326C',
 'TRPJHTP128F428B761',
 'TRGSNFQ128E079666C',
 'TRIQVNA128F92F9292',
 'TRCWMQH128F1458F9A',
 'TRXLWGU128E0793E91',
 'TRJWEET128E07824D7',
 'TRJSBTM128E0793324',
 'TRUIMDG128F425B0CB',
 'TRJKZTC128F14676A9',
 'TRLSCIQ12903CFDBEE',
 'TRPXVJJ12903CE52E8',
 'TRXIIEV128F149967D',
 'TRTWCUM128F92DF90A',
 'TRFVTOB128F4284E6C',
 'TRRIRMX128F92E6272',
 'TRXXVOG128F92F411D',
 'TRHOANO128F93269FD',
 'TRJHWXA128F4241A77',
 'TRUFZQU128F92D3C0C',
 'TRGNBHM128F92E1FE8',
 'TRKRUFV12903CB7907',
 'TRBGJPM128F93048FA',
 'TRSNQZA128F92E7CF9',
 'TRLQLWF128F14A46CF',
 'TRSRHXX128F4292252',
 'TRSDIDC128F92CD1AF',
 'TRDKIET128E07817EF',
 'TRYSJOT12903CA7352',
 'TRXFTDO128F429884C',
 'TRWGTXL128F92C3C03',
 'TRPXRIO128F92E805C',
 'TRYBBYX128EF3676BA',
 'TRPDRWH128F148DAC3',
 'TRHBUZD128F92E08BB',
 'TRISNHO128F9335979',
 'TRHLTZE128F92E16C7',
 'TRWCDLM128F92EB738',
 'TRXRIAE12903CF374B',
 'TRIGTIQ128F14979A3',
 'TRGTVAI128F426AA6A',
 'TRTTBED128E0782827',
 'TRCSNKA128F4298F10',
 'TRASNUX128F425EAF2',
 'TRGKJBQ128F92F8400',
 'TRPPUVJ128F93259A2',
 'TRMLXNN128F9320611',
 'TRGRMRM128F931D5A6',
 'TRYLDDB128F1474B86',
 'TRJJSAD128F4256B0D',
 'TRHFEYK128E078221F',
 'TRBAHID128E078460C',
 'TRPORHV128F9322512',
 'TRWQINA128F9339E57',
 'TRAKSYI128EF349B16',
 'TRLMHXN128F42311CF',
 'TRUNBFC12903CB2CCC',
 'TRJVZXB128F4279308',
 'TRBPTYF128F423EEA3',
 'TRSEGHR12903CA636D',
 'TRZJFZJ128F92D425E',
 'TRYYDLF128F423BB17',
 'TRQSHBF128F931FEB3',
 'TRESGUW128F935A63B',
 'TROHDFD128F148DAC1',
 'TROXMUA128F1491A41',
 'TRWNPDZ128F934B946',
 'TRRSZKD128F933D41E',
 'TRJPXVK128F425DD62',
 'TRAIRVL12903CFFE57',
 'TRXLPRQ12903D05327',
 'TRPFSJI128F422F31A',
 'TRDIEON128F934B4CD',
 'TRYFNSK128F422A87E',
 'TRNXDPM12903CF42A5',
 'TRSAPWL128F42ADC99',
 'TREHGFD128F4291EEA',
 'TRDPYZA128F42ADC95',
 'TRUGUEN128F426D379',
 'TRPZMCK128F934C24E',
 'TRUOFKL128F92EC215',
 'TRNXRUA128F428DF45',
 'TRLUZQN128F934B6E6',
 'TRRVEDO128F147B0C9',
 'TRJCTNF12903CF4558',
 'TRJSTRA12903CCA6E9',
 'TROOJUG128F9336CAC',
 'TRTYWFZ128F14554AA',
 'TRVPSXF128F429A6BF',
 'TRKCMIK128F92FFE9E',
 'TROQFSN12903CA1863',
 'TRDBQXT128F4289423',
 'TRQJABG128E0797559',
 'TRQNSPZ128F92C4289',
 'TRRPHWN128F92EAA46',
 'TRJJYOO128F428D132',
 'TROOXSL128E07938D0',
 'TRCIWSN128E07813EF',
 'TRADKAX128E0786B92',
 'TRSXNFR128F42720D7',
 'TRGBSRK128F931B0CC',
 'TROLZNQ12903CF5569',
 'TROLJKM128E07911F2',
 'TRGZUKV12903CC2F22',
 'TROVIUK128F145A17F',
 'TRQOUMO128F9324F05',
 'TRPAZUX128F4248272',
 'TROIVZG128F9326122',
 'TRSFLLX128F932732F',
 'TRGNOFL128EF34E4D5',
 'TRYZNFT12903CEA9CA',
 'TRKYVCE12903CE7DFF',
 'TRXHVDF128F425DF35',
 'TRZGATD12903CC67CE',
 'TRHFEMY128F14979BA',
 'TRKFBPS128F429617A',
 'TRHREOY128F427CA2F',
 'TRJHGUB128F427207E',
 'TRMOSYZ128F42B53F0',
 'TRQPJRL128F930F4B6',
 'TRWWMPL128F429EB4C',
 'TRRAXGA128F14B0F43',
 'TRVKTHJ128F424D875',
 'TRZUUKG128F145F98A',
 'TRRECVV128F9305DFA',
 'TRSJSRS128F42A0E8A',
 'TRITVUB128F42B81FF',
 'TRUBOJX128F425B710',
 'TRAKXMS12903CB36F2',
 'TRELLMP128F93231E7',
 'TRLIGMU128F932BC0B',
 'TROIXIC128F427B6F6',
 'TRQZHAY128F424E1C4',
 'TRNGQCW128F427B6E7',
 'TRYDOBY128F92E87F0',
 'TRDWPGB128F42B63B2',
 'TRPLPIN12903CE9E20',
 'TRYCJTW128F930B04F',
 'TRCFCHH128F425979D',
 'TRZIAXW128F423AEEA',
 'TRADNPB128F423AEE7',
 'TRXSVSQ128F42AA367',
 'TRDAUKE128F92FA056',
 'TRTJSAM128F429B015',
 'TRVPSVL128F92FA043',
 'TRQQGNY128F92E7F58',
 'TROFKRA128F4259B35',
 'TRQMAJC128F4285821',
 'TRNGKOQ128E0780DAC',
 'TRTQACQ128F1474D68',
 'TROUZEX12903CAF69C',
 'TRSIMWV12903CD1951',
 'TROEAFF128F145555B',
 'TROHHFF12903CC6E0D',
 'TRGWWIQ128F148FE2B',
 'TRMYAYJ128F934D0AF',
 'TRUUZVA128F4257957',
 'TRFULNM128E07969E2',
 'TRMOOPG12903CA5D90',
 'TRAVLLN128F14744C0',
 'TRLQFFX128F92F4917',
 'TRFJOHD128F42B9D53',
 'TRVVBLV128F42376DD',
 'TRLIZQF128F934EEF8',
 'TRPZKNH128F9313030',
 'TROSUNC128F427E889',
 'TRRLHBX128F9343438',
 'TRPIKYH128F92C7011',
 'TRNYCAH12903CB19F2',
 'TRILOWN128F426080F',
 'TRULHLZ128F42BB903',
 'TRMATIZ12903CA7203',
 'TRQZFVP128F4298DD3',
 'TRTESQR128E078DF6B',
 'TRUJFWF128E0792353',
 'TRITKQV128F424F08A',
 'TRJMUOT128F4275ED7',
 'TRIHCKH128F931FA72',
 'TRDDJFQ128F4295772',
 'TRUJCEF128F92ECE4E',
 'TRFQMSW128F426205E',
 'TRAAFGQ128F427D884',
 'TRYBVUJ12903CE26A1',
 'TRPEWCY128F427AAF4',
 'TRADRVX128F93322BF',
 'TRZQWLN128F426235E',
 'TRVSLCD128E079268B',
 'TRSIKBL128F427F430',
 'TRBAKKG12903CE896B',
 'TRWLBLZ12903CE895E',
 'TRNCEUK12903CCC629',
 'TRDGOCB128F933B3C2',
 'TROUTTW128E0781726',
 'TRSZHKH128E078172B',
 'TRYMOTL128F42633DD',
 'TRYZTNS128F93617F3',
 'TRILUPC128F9300BC4',
 'TRISITF12903CE60D2',
 'TRKOZAA128F9325176',
 'TRYLOOI128F1453045',
 'TRHHYQQ128F42BB341',
 'TRUCSBP128E078B714',
 'TRPYEIS128F92F85B8',
 'TRNEOHC128F4289D51',
 'TROWUZD128F1465363',
 'TRQPYWK128F4289D59',
 'TRUDXEG128F9345084',
 'TRVQBRZ128F423EEDC',
 'TRFTIBW128F1479218',
 'TRIWOBB128F425D5BB',
 'TROBYUK128F9335CA7',
 'TRYRXZK12903D0C385',
 'TRYUHKT128F42393D9',
 'TRRPLCA128F149965D',
 'TRBPBYN12903CC78B0',
 'TRHJSEZ128F1459DCC',
 'TRALASU128E07899DB',
 'TRTDWNH128F14859BC',
 'TRGTSTW128E0792348',
 'TRESOEA12903CB4F7B',
 'TRJNZIZ128E07929A9',
 'TRUGIST128F427BBE8',
 'TREQSKD128F932E74A',
 'TRHPKWO128F92E01D5',
 'TRWOXPU128F92EB3D3',
 'TRRVSBS128F425A7B0',
 'TRJHSKL128F92E4EC7',
 'TRYIOWV128F92DE2D1',
 'TROXLCI128F92F25A7',
 'TRDJZAT128F428BA7D',
 'TROWBBZ128F4276E15',
 'TRDGROB128F934B685',
 'TRUDQUD128F4267DCE',
 'TRJCKDH128F428C725',
 'TRHEIAI128F92C2E28',
 'TRICALF128F9310064',
 'TRFCJQR128F4240D6B',
 'TRVTJJE12903CD43DF',
 'TRHUHEI128F4288BD4',
 'TROARTG128F42732C6',
 'TRQEHWY128F92E525E',
 'TRPYUHI128F92D026D',
 'TRCVAUX128F428A4A2',
 'TRHOEPA128F4259F3F',
 'TRAGOUM128F4286CDE',
 'TRCAQRA128F4286CE4',
 'TRBCJSZ128E07969B5',
 'TRTRUPP128EF34B5BA',
 'TREGNMG128F932C0C2',
 'TRNXKBJ128F1496267',
 'TRVYHYN128F4281AEB',
 'TRLCQDM128F9333628',
 'TRHBABG128F4281C8E',
 'TRRHDGZ128F9340B22',
 'TRKYKCH128F92CB667',
 'TRXRZLJ12903CE26A2',
 'TRRSYUN128F932F7E2',
 'TRYDCEO128F4262926',
 'TRWDWIE128F92C6851',
 'TRVJAUG12903CC4945',
 'TRCFLPF128E078115B',
 'TRGNEIO128F14563CB',
 'TRLEODD128F428CA7D',
 'TRJIJRM128F4293F1E',
 'TRGUSWI128F92EBA20',
 'TRYINMA128F931D77D',
 'TRSNJKO128F145A1C1',
 'TRZJZHR128F4255BE1',
 'TRANTFM12903CA834C',
 'TRXGAUO128F425F12F',
 'TRRAOED128F4284764',
 'TRERUDZ128F1465259',
 'TRHXELM128E07820C9',
 'TRXBHXO128F1458F38',
 'TRZBCON128F932BBAE',
 'TRNEIBT12903CC71F9',
 'TRGWUKX128F9329052',
 'TRFNUVT128F92F9011',
 'TRLZIRJ128F42814D4',
 'TRJHVWR12903CD1971',
 'TRYZIBN128F4286514',
 'TRFTEJK12903CDB30A',
 'TRWACTS128F932C2C2',
 'TRYIVTN128F4286515',
 'TRXWBRB128F931C962',
 'TRDYCVB128F9327262',
 'TRTEOTK128F930F4B8',
 'TRFTTMD128F93112C3',
 'TRDIMIJ128F1464D53',
 'TROGOTM128F92F80D5',
 'TRVJRSA128F92E4FFA',
 'TRHXMQR128F42ACE88',
 'TRJTJAO128F42ACE87',
 'TRCSZKA12903CA0E4C',
 'TRWTPYD12903D03AE9',
 'TRYRZRK128F4228CD0',
 'TRXNONC128F425C2DC',
 'TRJWAGV12903CDAF0B',
 'TRHUVQV128F425BCE1',
 'TRRNOUT128F425DCF5',
 'TROYOWO12903CACF51',
 'TRQUYCQ128F427AE73',
 'TRRLGDR128F933A7C9',
 'TREUDYW128F92FCDC1',
 'TRVBFHW128F147CC96',
 'TRIPLSI128F9343267',
 'TRRIBYA128F934D0DD',
 'TRUKUBH128F424AAB5',
 'TRHHSEG128F1452B6B',
 'TROXHEA128F146EC58',
 'TRCCPUL128F4285F96',
 'TRPZDPB128F93123BF',
 'TRVEEYH128F930958B',
 'TROKJRN128F14683A2',
 'TROMKRY128E078957D',
 'TRNGAUB128F92E65FF',
 'TRWCCRR128F935A65A',
 'TRERDDF128F428ECC4',
 'TRDBPTY128F425A2FA',
 'TRTUVGU128F9351A23',
 'TRUDFCZ12903CC3E61',
 'TRUYHSK128F425B009',
 'TROIBCX128E07984B8',
 'TRZWTWF128F931BAD9',
 'TRKMGLK12903CBCA80',
 'TRIZKGE128F1457420',
 'TRAGABG12903CEC68B',
 'TRPKOGH128F932D5D8',
 'TRKSDZM128F9346B87',
 'TRCPTEO128F92E0176',
 'TRKIKPQ12903CEE3BA',
 'TRIQUEM128F149D971',
 'TROBNEK128F148AE08',
 'TRMPLQW128F93465FA',
 'TRUCIRG128F93450A1',
 'TRMFITQ128F425DC36',
 'TRFDEKP12903D027CA',
 'TRGGKNK128F9334948',
 'TROLIFB12903CC4944',
 'TRITEGR128F422DA64',
 'TRGMNEE128F146AAD9',
 'TRJYEYR128F1476806',
 'TRIWMGU128F92F4121',
 'TRRZLBQ128C71967A0',
 'TRNSAXS128F427EF31',
 'TRUSCOI128F147DF6C',
 'TRBJRZH128F429EA62',
 'TRIROYA12903CE1794',
 'TRLLIGO128F9318CA6',
 'TRRZJVQ128E0780DB1',
 'TRFGMTD128F4284394',
 'TRDRBHT128F4295BE6',
 'TRLRGAB12903CE38D4',
 'TRFOWKQ128F42BBB3C',
 'TRDOZUR128F1465A75',
 'TROISGI128F4266028',
 'TRPGHIS128F932A4AA',
 'TRFYUOO128E07934F5',
 'TRAJEDW12903CA8E70',
 'TREJRVZ128F932732E',
 'TRIRJOU128F145F994',
 'TRLJNMJ128F429593B',
 'TRCEKZA128F4241811',
 'TRLVIOH128F92FD558',
 'TRACEJW128F42BA8D5',
 'TROLWOI128F425EF06',
 'TRCPOAD12903CB04A4',
 'TREXITL128F421DF49',
 'TRJKRWX128F423AAF6',
 'TRBKPQA128F42972B0',
 'TRWCKEI128E0780E47',
 'TRYQJEA128E0799395',
 'TRVJEKC128F427399F',
 'TRGGNNH128F42599C3',
 'TRRTAMR128F92E28DF',
 'TRSQCGA128F92E28E4',
 'TRRHXZX128F93191C4',
 'TRLSNDQ128F4266BD7',
 'TRPAAME128E0791267',
 'TRAEBCS128E0782FC6',
 'TRWNMTS128F4295233',
 'TRBXGPR128E078E9B0',
 'TRKBFWO12903CEAF7F',
 'TRIHPOR128F9320A3D',
 'TRRPSDS128E078A338',
 'TRNQOVC128F427A835',
 'TRXDUOG128F4258B33',
 'TRSUZZR128E0786B9B',
 'TRAKOUW12903CD9C62',
 'TRVVZAV128F424889B',
 'TRDNCZR128F147DF6F',
 'TRMGWRE128F429FEF5',
 'TRXGXCK128F14900F1',
 'TRKRRIW128F424D7FD',
 'TRXMRHK128F424D805',
 'TRPJSJF128F14525B7',
 'TRMVQBH128F4253914',
 'TRNDKRX128F14525CF',
 'TROYORO128F92EA2C6',
 'TRSYCDY12903CF5CA5',
 'TRSDEXS128F4293B8C',
 'TRMMAIV128F92E7F55',
 'TRFHHKY128F92E6AE9',
 'TRARUGW128F92FEBE0',
 'TRFYIMN128F93274D9',
 'TRSLKTL128F92F278A',
 'TROXLVM12903CDF148',
 'TRMDWTO128F4269C7C',
 'TRPDVBK128F92FFEA1',
 'TRFAEPZ128F427AFB2',
 'TRDTKOY128E07953E5',
 'TRCYZNE128F933CB64',
 'TRIXIPX128F42683A1',
 'TRKEDKN128F1499A40',
 'TRTSFUN128F1455B70',
 'TRCEGOJ128F425B050',
 'TRLHWCW128F428BF29',
 'TRJQCWO128E078199D',
 'TRDQNUD128F428AFEA',
 'TRNLCEN128F428AFE6',
 'TRXWGZA128F9303F0C',
 'TRYSBGA128F92DE2F1',
 'TRSALSU128E07864C5',
 'TRTJCAD128E078D3CE',
 'TRHOINK128E078FEA3',
 'TRAKKVD128F14A895B',
 'TRJHXEO128F425C34E',
 'TRCBESC12903CFADD9',
 'TRJVHFX12903CB74BF',
 'TRQNRTL128F9315FD3',
 'TRPXVTD128F93411C4',
 'TRKRBIA128F145C03A',
 'TRNFIKK128EF350B92',
 'TRROPQP128F42631A2',
 'TRBFYSE128E0783EA5',
 'TRAARZE128F93264E9',
 'TRRRIUK12903CFB054',
 'TRDDJYF12903CFB066',
 'TRCUNLK128F93199D2',
 'TRGWGOF128F4241B03',
 'TROXLXH128F4289FD7',
 'TRELXKT128F147EDB5',
 'TRRJATE128F1458516',
 'TRPXYXU128F428AE4B',
 'TROZQDF128F92E38C6',
 'TRMFHKK128F4270628',
 'TRVVLJS128F149E710',
 'TRVHEDH128F4243651',
 'TRYEGBI128E0795767',
 'TRFOIIO128F1490EEC',
 'TRCGXXW128F145E1A0',
 'TRKTQTV128F42996FC',
 'TRHUVAN128F42996FB',
 'TROLKOL128F425F71F',
 'TRFQTGT128E07929D3',
 'TRMCZWO128F422F61E',
 'TRTWQYX128F14794E7',
 'TRTVXYR12903CCAE2F',
 'TRZDFXU128F428FD54',
 'TRDKEWM128F145267A',
 'TRRTAHX128F421427A',
 'TRCGXSS128E07819CC',
 'TRWTKZY128F4241A9D',
 'TROWFMN128F4268150',
 'TRHWFED128F9307C70',
 'TRIUFXI128E0788E4A',
 'TROHWZM128F148251B',
 'TRXIQDL128F92F27DC',
 'TRYNVIG128F42345A6',
 'TRBPBNS128F42B8623',
 'TRAJSLD128E0792188',
 'TRLHVLT128F424E3B9',
 'TRQVHAB128F4266501',
 'TRPEEJJ128E0792EF5',
 'TRRSOIC128F9343B94',
 'TRAKXEJ128F92E1FD6',
 'TRDGZKY128F4218F49',
 'TRQRGCS128F4293F6C',
 'TRNWJBH128F4258D16',
 'TRXIJRV128F427C258',
 'TRYDFNJ128F1460DC5',
 'TRSPOSQ128F92D679E',
 'TRYJEDG128EF340E65',
 'TRRNUJD12903CEBBC8',
 'TRUQARX128F426BAF2',
 'TRIMYUE128F92EBF0B',
 'TRZWZGO128F1489837',
 'TRPIMFA128F426EC1B',
 'TRVZACQ128E0780E39',
 'TRSCUEW128E0781CB8',
 'TRYKKMQ128F92E5255',
 'TRETMFW12903CA2DE4',
 'TRRTUND128F429B12D',
 'TRCIIAD128E07993BF',
 'TRJSGCE12903CB5C34',
 'TRBTRIY128F1499842',
 'TRXIVES128F426B303',
 'TRFJIOA128E0781CB7',
 'TRAPLSD128E0781A94',
 'TRGXBBJ128F9305E0A',
 'TRMBVAW128F9335A10',
 'TRHBNSC12903CEA41C',
 'TRBRUCX128EF35EF44',
 'TRHDUGA128F931B4A7',
 'TRUECPO128F9304306',
 'TREYKTG12903C951C9',
 'TREVWZR128F933B440',
 'TRPNSOE128F427CCDF',
 'TRICOBK128E0791E5E',
 'TRKHYKB128E0789D42',
 'TRGUNET128F42590AB',
 'TRHRESZ128F92FDB41',
 'TRPCTNN128E07899A6',
 'TRTGLBA128F4285C59',
 'TRENBWT128E0793881',
 'TRDREZS128EF34337B',
 'TRTFOSN12903CBD7D0',
 'TRZBDLW12903CB551F',
 'TRLTTKM128F9303419',
 'TROUAEG128F429354A',
 'TROAVNM128F92E120C',
 'TRDJEJV128F4263881',
 'TRMIJQB128F92F5DE4',
 'TRTVGUL128F92FC140',
 'TRSDPJI12903CBD7C2',
 'TRZFGAB128F425987B',
 'TRIREMN128F4295BE4',
 'TROJUDY128F9339983',
 'TRZATRK128F424801A',
 'TRPYWQA128EF348613',
 'TRGIJKQ128F930020D',
 'TRVIZNU128F4260D83',
 'TRAAJJW128F4298683',
 'TRIXMLV128F42724B1',
 'TRSGXPQ128F9306C04',
 'TRXTTMJ128F92FFC02',
 'TRAQQDK128F42865B6',
 'TRBIHAU128F425C317',
 'TRPSZWH12903CF053F',
 'TRJPMWW128F930868F',
 'TRWXGNI128F92FEA92',
 'TRAGQLG128F9351109',
 'TRQDKBK128F42B91C0',
 'TRDDZOS128F42B91EC',
 'TRGCCDN128F1477678',
 'TRAIXXC128F1466EC9',
 'TRRDYQW128F9302C5D',
 'TRGZDEG12903D05420',
 'TREPTVD128F422B929',
 'TRORRYB128F427B0FA',
 'TRRYSUZ128F933CE81',
 'TRVLGZE128EF3466D3',
 'TRQQOVX12903CF0A2B',
 'TRHAAWC128F424D8A8',
 'TRMTPJF128F428F617',
 'TRIEBUS128F421BD4C',
 'TROHMSX128F421BD45',
 'TRYZJKT128F422B280',
 'TRJUZQW128F93224D1',
 'TRUCNCH128F426A4B3',
 'TRMJJZK128F425F1C3',
 'TRWFQNY128F4266004',
 'TRMPGPC128F42AF55E',
 'TRSFKJQ128F423DF9C',
 'TRCZUXJ128F931B7C2',
 'TRGEIPC128EF357B2F',
 'TRRVFSC128F9339096',
 'TRQAXAB128E078E82D',
 'TRVUAWZ128E079234D',
 'TRCPZGY128F428BCBA',
 'TRVUOCF12903CACED8',
 'TRDJUDF128F9345173',
 'TREQPAD128F92D73A0',
 'TRMBBAL128F92E4B44',
 'TRSIOBS128E07896BA',
 'TRSOYTK128F14A94EB',
 'TRLKZPJ128E0792BF7',
 'TRACTTC128F42370D9',
 'TRDFMBA128E078B02A',
 'TRQUNLN128F1482523',
 'TRFYQUV128F931957E',
 'TRGXZPB128F428FB74',
 'TRLVRVU12903CF2B53',
 'TRGBYJF128F146A362',
 'TRTCQSQ128F9305F00',
 'TREUMUD128E0780CF3',
 'TRWTEOG128F931C79B',
 'TRUVGUB128F9309727',
 'TRCRWRS128F425B98F',
 'TRRSKRE128F92CA523',
 'TRSRMRF12903CD5210',
 'TRRJHNB128EF351BF1',
 'TRVKTGD12903CF8ACA',
 'TRHGYNY128F4227D8B',
 'TRXSOYO128F9343CC5',
 'TRXLSSY128F92C7A2F',
 'TRVVTCO128F429BED1',
 'TRLRXKI128F92EA27B',
 'TRJDTBE128F4289421',
 'TRIMMJZ128F92FCE0A',
 'TRCVHUK128EF343A64',
 'TRHESIQ128F42AE3BB',
 'TRALBKD128F92F456D',
 'TRHGRNX128E07923CE',
 'TRCTJJN128F1461F0A',
 'TRGEOIU12903CB7037',
 'TRARKGW128F92EB8F9',
 'TRMIAQM128F4277AC3',
 'TRJESFZ12903CA5AB3',
 'TRKLANE12903CDE48C',
 'TRHOQVZ128F9305E5B',
 'TRKGOUE12903CF4702',
 'TRXKBPT128F92D63A9',
 'TRAYFDQ128F145FB6B',
 'TREGTLA128F1455584',
 'TRXJCGM128F932D16B',
 'TRFDEBX128F92D541A',
 'TRVDMOQ128F9350943',
 'TRQPMHV128F932F5F1',
 'TRGDWQU128F92CBC84',
 'TRBXPHJ128F92FFA98',
 'TRRFOZB128E0789072',
 'TRIPKBL128F931713D',
 'TRSCDAV128F92CBE75',
 'TRYRJBY128F932A090',
 'TRJDYZI128F1485051',
 'TRIXQAE128F4242815',
 'TRGPGKN128F935A667',
 'TRGPZOH128F14649C6',
 'TRLLBVB128F429E997',
 'TRVYFNI128F4281A4E',
 'TRACFAP128E07862C1',
 'TRRHQHV128F1497E58',
 'TRWVTKY128F42590AD',
 'TRFYSUQ128F932EF46',
 'TRIPAUX128F934B53F',
 'TRMOIRF128F9302F2E',
 'TRDAHRF12903CBB9CB',
 'TRAPZYQ128F42926B3',
 'TRKVDGI128F1455B6D',
 'TRKBZZZ128F4272F8D',
 'TRWUOYA128E078BFEC',
 'TRHEEOV128E0795CD5',
 'TRPMGDU12903CF3068',
 'TRQIMKV12903D0195D',
 'TRZZKGN128F42B5CC5',
 'TRCOSFN128F426D2F3',
 'TRWNUWU128F428BA7C',
 'TRQJTMF12903CB80DF',
 'TRKCBAC128F9326101',
 'TRRIUHG128F424364B',
 'TRUMBAH128F1485B10',
 'TRKZCWR128E0785D71',
 'TRCQYBK128F92C6AF5',
 'TROKJXM128F424F9A5',
 'TRYMMAY128F930277D',
 'TRGQPYP128F9323754',
 'TRFQBRH128F92F291A',
 'TRLXDBE12903CF107C',
 'TRPJJUF128F933FE56',
 'TRWILVQ128F42644B3',
 'TRMCEJS12903CAC331',
 'TRULPQQ128F423A3D8',
 'TRASMZT128F427F46A',
 'TRSCSAW128F426578C',
 'TRSCWJC128F931A2F5',
 'TRVHPEU128F42882B2',
 'TRUJJCD128F42456FA',
 'TRIPBXB128F425BD44',
 'TRFESBJ12903CC3C89',
 'TRVQKED128F934C121',
 'TRPYLPO128F934C11E',
 'TREKJPL128F934B684',
 'TRORBHC128F42AD0F4',
 'TRSMAUP12903CBB9CE',
 'TRKWUFI128F42B1B3A',
 'TRZMHCI12903CCDEA6',
 'TRVHAJW128F427E694',
 'TRTBJAV128EF351B68',
 'TRAPHPQ12903CF2196',
 'TRCWZGP12903D0591A',
 'TRDOGIT128F4263321',
 'TRHPNSF12903CE6C2A',
 'TRNDYZC12903CEBC9A',
 'TREBAMB128F930C1B0',
 'TRFIWCV128F930C1C1',
 'TRJTVOT12903CCC5C9',
 'TROCVJH128F4230F41',
 'TRLZBCJ12903CB07AC',
 'TRAWTZW128F9318416',
 'TRNEOIW128F93437D7',
 'TRKVFYV128F9326705',
 'TRNXRET128F148D5FD',
 'TRSKLHF128F428BCF8',
 'TRNISEE128F933908A',
 'TRZPHVT128F4298109',
 'TRTSDOX128F9339B9A',
 'TRBZKDX128F4255A4A',
 'TRBCALP128F933905E',
 'TRIPAVV128F1456A0F',
 'TRESWCO128F4257C17',
 'TRQJPSL128F92F0280',
 'TRBRCDJ128F427EEF8',
 'TRNFLXR128E0793B8A',
 'TRNGANC128F4255F56',
 'TRBOHVZ128F9336973',
 'TRMVCVS128F1468256',
 'TREJITG128F148F906',

In [14]:
filtered_songs = songs_df[songs_df['track_id'].isin(unique_track_ids)]
filtered_songs.reset_index(drop = True , inplace = True)

In [15]:
filtered_songs.shape

(30459, 4)

In [27]:

import dask.dataframe as dd
import numpy as np
from scipy.sparse import csr_matrix

# Step 1: Load data with Dask
# Assume the dataset is in a CSV file

df = dd.read_csv(users_data_path)

# Step 2: Ensure playcount is numeric
df['playcount'] = df['playcount'].astype(np.float64)
df = df.categorize(columns=['user_id', 'track_id'])

# Step 3: Convert user_id and track_id to numeric indices
# This is necessary for creating a sparse matrix later
user_mapping = df['user_id'].cat.codes
track_mapping = df['track_id'].cat.codes

df = df.assign(
    user_idx=user_mapping,
    track_idx=track_mapping
)

In [28]:
df.head()

,track_id,user_id,playcount,user_idx,track_idx
0,TRIRLYL128F42539D1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1.0,691377,10705
1,TRFUPBA128F934F7E1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1.0,691377,7334
2,TRLQPQJ128F42AA94F,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1.0,691377,14212
3,TRTUCUY128F92E1D24,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1.0,691377,23206
4,TRHDDQG12903CB53EE,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1.0,691377,8936

In [29]:
interaction_array = df.groupby(['track_idx','user_idx'])['playcount'].sum().reset_index()

In [30]:
interaction_array.head(10)

   track_idx  user_idx  playcount
0          0     15780        3.0
1          0     76968        1.0
2          0    134525        2.0
3          0    231541        1.0
4          0    305348        1.0
5          0    587045        1.0
6          0    591458        1.0
7          0    593674        1.0
8          0    610079        2.0
9          0    611454        1.0

In [31]:
row_indices = interaction_array['track_idx']
col_indices = interaction_array['user_idx']
values = interaction_array['playcount']

In [32]:
n_tracks = unique_track
n_users = unique_users

sparse_matrix = csr_matrix((values , (row_indices , col_indices)) , shape = (n_tracks , n_users))

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
np.where(df['track_id'].cat.categories == 'TRIRLYL128F42539D1')

(array([10705]),)

In [53]:
def collaborative_recommendation(song_name,user_data,songs_data,interaction_matrix,k=10):
    # fetch the row from songs data
    song_row = songs_data[songs_data["name"] == song_name]
    print(song_row)
    # track_id of input song
    input_track_id = song_row['track_id'].values.item()
    print(input_track_id)
    # index value of track_id
    ind = np.where(user_data['track_id'].cat.categories == input_track_id)[0].item()
    print(ind)
    # fetch the input vector
    input_array = interaction_matrix[ind]
    # get similarity scores
    similarity_scores = cosine_similarity(input_array, interaction_matrix)
    # get top k recommendations
    recommendation_track_ids = df['track_id'].cat.categories[np.argsort(similarity_scores.ravel())[-k-1:][::-1]]
    print(recommendation_track_ids)
    # get top scores
    top_scores = np.sort(similarity_scores.ravel())[-k-1:][::-1]
    print(top_scores)
    # get the songs from data and print
    temp_df = pd.DataFrame({"track_id":recommendation_track_ids.tolist(),
                            "score":top_scores})
    print(temp_df)
    top_k_songs = (
                    songs_data
                    .loc[songs_data["track_id"].isin(recommendation_track_ids)]
                    .merge(temp_df,on="track_id")
                    .sort_values(by="score",ascending=False)
                    .drop(columns=["track_id","score"])
                    .reset_index(drop=True)
                    )
    return top_k_songs

In [54]:

collaborative_recommendation(song_name="Crazy in Love",
                             user_data=df,
                             songs_data=filtered_songs,
                             interaction_matrix=sparse_matrix)

                track_id           name   artist  \
3337  TROINZB128F932F740  Crazy in Love  Beyoncé

                                    spotify_preview_url
3337  https://p.scdn.co/mp3-preview/807828ea7070bda7...
TROINZB128F932F740
17018
Index(['TRZZZRJ128F42819AF', 'TRZZZHL128F9329CFB', 'TRZZZCN128F9317A03',
       'TRZZZCL128F428BB80', 'TRZZYMU128E0792400', 'TRZZXVN128F93285B4',
       'TRZZXOQ128F932A083', 'TRZZXJT128F931D72C', 'TRZZXIR128F9308AD4',
       'TRZZVMG128F149B9A2', 'TRZZUTD12903CADD68'],
      dtype='string', name='track_id')
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
              track_id  score
0   TRZZZRJ128F42819AF    0.0
1   TRZZZHL128F9329CFB    0.0
2   TRZZZCN128F9317A03    0.0
3   TRZZZCL128F428BB80    0.0
4   TRZZYMU128E0792400    0.0
5   TRZZXVN128F93285B4    0.0
6   TRZZXOQ128F932A083    0.0
7   TRZZXJT128F931D72C    0.0
8   TRZZXIR128F9308AD4    0.0
9   TRZZVMG128F149B9A2    0.0
10  TRZZUTD12903CADD68    0.0

,name,artist,spotify_preview_url
0,Solo Dolo (Nightmare),Kid Cudi,https://p.scdn.co/mp3-preview/66373133ca4e7ebc...
1,After,Ihsahn,https://p.scdn.co/mp3-preview/d566307f9eb10478...
2,Day Five: Voices,Ayreon,https://p.scdn.co/mp3-preview/9f62f3a9d9a232a6...
3,Big Wiggly Style,The Devil Wears Prada,https://p.scdn.co/mp3-preview/39bf3d8d7d027e44...
4,Dead Season,Nujabes,https://p.scdn.co/mp3-preview/14d665ba14f7b548...
5,Lord Anthony,Belle and Sebastian,https://p.scdn.co/mp3-preview/c7835d4b82ca1392...
6,Cover Up,Imagine Dragons,https://p.scdn.co/mp3-preview/382d85deaca4e3e4...
7,The Ship of Pills and Needed Things,I Am Ghost,https://p.scdn.co/mp3-preview/331a9b39765bade1...
8,Flutter Girl,Chris Cornell,https://p.scdn.co/mp3-preview/086e8821cd2cf926...
9,Abschied,Sopor Aeternus & The Ensemble of Shadows,https://p.scdn.co/mp3-preview/3d825e9605292f57...
10,Coils,Robert Rich,https://p.scdn.co/mp3-preview/767efe836ec7a099...